name: mac-release-build

# TODO: あとでリリースタグ作成時に変更する
on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.1
        with:
          name: Build
          command: build
          args: --release
      - uses: actions-rs/cargo@v1.0.1
        with:
          name: Test
          command: test
          args: --release
      - name: Create zip
        run: |
          zip --junk-paths target/release/pomors_mac target/release/pomors
      - uses: actions/upload-artifact@v1
        with:
          name: pomors_mac.zip
          path: target/release/pomors_mac.zip
