name: release-to-cratesio

on:
  release:
    types: [published]

jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Build env
        run: |
          sudo apt-get update
          sudo apt install libdbus-1-dev libsdl2-dev
      - name: login
        run: cargo login $CRATESIO_TOKEN
        env:
          CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
      - name: dry run
        run: cargo publish --dry-run
      - name: publish
        run: cargo publish
